# Generated by Django 3.1.2 on 2020-10-13 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('message', models.TextField()),
                ('contact_date', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Emails',
            },
        ),
    ]
