# Generated by Django 3.1.2 on 2020-10-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('contact_date',), 'verbose_name_plural': 'Emails'},
        ),
    ]
