# Generated by Django 3.1.2 on 2020-10-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About Section'},
        ),
        migrations.AlterModelOptions(
            name='bulletpoint',
            options={'verbose_name_plural': 'Bullet Points'},
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name_plural': 'Index Content'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
    ]
