# Generated by Django 3.1.2 on 2020-10-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20201012_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='description12',
            new_name='description2',
        ),
    ]
